### ISSUE TITLE
problems opening a file on Windows

### ISSUE THREAD

**Issue by muellerto** [leo-arch/CliFM#354]
**Describe the bug**
In several situations it's not possible anymore to open a file. The most prominent candidate is the own `clifmrc` by pressing F10 - `vi` opens but the file in it is unknown (and empty).

**To Reproduce**
Just press F7, F8, F9, F10 or F11 on Windows. It works well on Linux.

(Interesting is: F1, F2, F3, F6 work as expected also on Windows.)

When the problem happens the editor executable is started but the filename (or its path) is not transferred correctly as parameter. When I examine the running editor process in this moment I see its command line is indeed

`"C:\Program Files\Vim\vim91\vi.exe" open`

`vi` doesn't say much in this situation. That's why it's good to have something else. When I start clifm in an environment where the `EDITOR` environment variable is not mapped on `vi.exe` it uses `notepad.exe` as default editor. When I then press F10 `notepad.exe` says `open.txt` is not a file - this means: it gets indeed this mysterious `open` as parameter and adds its default extension `.txt` himself.

There's also another situation: opening a file using the actual MIME settings. When I have an `.odt` file (LibreOffice text file) in the list and I type its ELN LibreOffice comes up but says `open` is not a file. This is also the case when I use the `ow` command and select an application from the MIME settings. When I type directly `soffice ELN` so that the MIME settings are not involved it starts always correctly.

**Expected behavior**
All these methods should open the desired file.

**Desktop:**
- OS: Windows 11 Pro 25H2
- Terminal: Hyper, Mintty, Alacritty (doesn't matter)
- Clifm version: 1.26.5
- Installation source: Git from today (the problem exists already for some days)

**Comment by leo-arch** [comment]
Hi @muellerto. This issue was most likely introduced by https://github.com/leo-arch/clifm/commit/c3f6ea8d98d4e3cbb692f1b18edd2b433c8b5c7e. Should be fixed now.

**Comment by muellerto** [comment]
Seems to work. Thanks a lot. I'll report here when I still get into a situation.
